Cargo.lock
Cargo.toml
src/main.rs

Actix-web can re-use a file descriptor instead of listening to a new port, which is used to hot-reload servers. In practice we aren't using that, and it makes things a little messy. In the interest of fewer dependencies and simpler code, I think we should remove it.

Remove unused dependency on listenfd

---

.circleci/config.yml
README.md

I chose codecov.io because there is an [CircleCI orb](https://circleci.com/docs/2.0/orb-intro/) that makes it very easy to  upload coverage. Most of the work here is getting the coverage tools installed. I plan to move this into mozilla/ci-docker-bases soon so we don't have to duplicate work every time.
Another note is that coverage requires a complete rebuild of the code (to add coverage instrumentation). After this lands and we start getting reports, I want to make CI only build the project once, or parallelize the coverage build.

Add coverage reports using codecov

---

src/main.rs

Closes #1 
```
$ ./target/release/classify-client
{"Logger":"classify-client-0.1.0","Type":"app","Pid":53803,"Severity":6,"Timestamp":1545429223825160000,"Fields":{"msg":"started server on https://[::]:8080"}}
{"Logger":"classify-client-0.1.0","Type":"request.summary","Pid":53803,"Severity":6,"Timestamp":1545429236252773000,"Fields":{"msg":"","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0","lang":"en-US,en;q=0.5","remoteAddressChain":"[::1]:62243","path":"/api/v1/classify_client/","method":"GET","code":200}}
```

Support path used by normandy

---

src/endpoints/dockerflow.rs

ref #29
I didn't find many examples to assert content-type headers, parse JSON body etc. And I must admit that I got stuck very quickly...

Add basic tests for Dockerflow endpoints (ref #29)

---

src/endpoints/dockerflow.rs

We missed these because CircleCI didn't run on #32. It didn't run because that PR came from a fork, which CircleCI had been instructed to ignore. I've turned on running CI from forks, and additionally made checks mandatory for merges.

Fix missed clippy problems

---

README.md

All of our CI coverage for the master branch is being reported for the staging branch that bors uses. This make it so the badge at least shows an accurate value. We should figure out how to make the master branch show correctly, however.

Update coverage badge to where the results are

---

src/endpoints/classify.rs
src/endpoints/debug.rs
src/endpoints/dockerflow.rs
src/endpoints/mod.rs
src/geoip.rs
src/logging.rs
src/main.rs
src/metrics.rs
src/utils.rs

I'm not confident about this change. I wanted to try and make `main` a bit smaller and more direct. To that end, I re-used the pattern I used for the metrics builder, and logging and geoip to use methods that take a settings object and return the right thing, instead of putting that logic in `main`. I also refactored logging to accommodate that.
@leplatrem I'd like feedback here about what you think of these changes, and about this pattern overall. If it is something we'd like to push forward with, I'll fix up the merge conflict and we can land it. I'd also be fine closing this PR unmerged.

Make main a bit leaner

---

bors.toml

We removed this from other Product Delivery products because it ended up being annoying. I forgot to change this one.

Remove required reviews from bors

---

.circleci/config.yml
Cargo.lock
Cargo.toml
Dockerfile
src/endpoints/classify.rs
src/endpoints/debug.rs
src/endpoints/dockerflow.rs
src/endpoints/mod.rs
src/geoip.rs
src/logging.rs
src/main.rs
src/metrics.rs
src/settings.rs
src/utils.rs

This is a large change, since actix-web changed significantly. It also removes
Sentry integration, because currently the Sentry integration with Actix does
not support actix-web 1.0.
The biggest change is that the geoip looks now happen on the same thread instead of a separate shared set of workers. This was a neat trick we did in the initial implementation. I know that it can be done with Actix 1.0, but I didn't want to take the time to figure out how to do it right now. I suggest we load test this implementation, and if it performs similarly to the other one, keep this simpler implementation.

Update actix-web to 1.0

---

.cargo/audit.toml
.circleci/config.yml
Cargo.lock

This is that the package is now unmaintained. This is not an immediate security problem that should block our CI.

Ignore RUSTSEC-2018-0015

---

src/endpoints/classify.rs
src/endpoints/dockerflow.rs
src/geoip.rs

...I don't know if that's the most sustainable way of fixing #87

Fix #87: pick up IP in US for heartbeat

---

renovate.json

Classify Client is essentially in maintenance mode, and doesn't need regular dependency updates.

Disable renovate

---

src/endpoints/classify.rs
src/endpoints/debug.rs
src/logging.rs
src/metrics.rs
src/utils.rs

Accessing application state changed in Actix Web 4, and I implemented the changes in #123 only incompletely. With this change, we always use the `Data` wrapper for the endpoint state, which fixes the problem.

Fix app_data access, which I broke in the Actix Web 4 upgrade.

---

.circleci/config.yml

Fix #121 
See https://github.com/mozilla/ci-docker-bases/issues/322

Fix #121: Remove use of ci-docker bases

---

src/main.rs

Adjusting paths for MLS sunset compatibility. MLS didn't use `/api` prefix.

Adjusting paths for mls compatibility

---

src/endpoints/country.rs
src/endpoints/mod.rs
src/keys.rs
src/main.rs

This is a followup from #152 . 
- Moved API key file loading to startup rather than lazy loading.
- Added error logging for if the api keys file is missing or cannot be parsed.
- Added test scenarios to verify logging worked as expected.

Moved API key loading/caching to startup. Added error logs and tests.

---

Dockerfile

Macking geolite DB optional in dockerfile build as it can be (is for production) mounted later.

Macking geolite DB optional in dockerfile build as it can be mounted later

---

src/main.rs

Ichnea handled all verbs for /v1/country, routing all verbs in the same way.
Hotfix.

/v1/country endpoint should handle all verbs, as ichnea did

---

Cargo.lock
Cargo.toml
README.md
src/endpoints/classify.rs
src/endpoints/country.rs
src/logging.rs
src/main.rs
src/settings.rs

Classify-Client is a little noisy. Adding log level filtering from `slog` and setting the default to Warning.
Updated read-me.
Fixed lint errors.

Adding log level filtering. Setting a default level to Warning

---

.github/workflows/publish.yml

For now, we only have a `workflow_dispatch` trigger to facilitate manual testing, but when this service is fully migrated to Argo, that trigger will be removed and the image will only be published on commits to `master` and semver tag pushes.
In the future, this workflow will:
- run on every pull request (but not push the image) as a CI step
- publish every commit to `master` as the new `latest` image
- publish every (semver) tagged commit as an image with that same tag and a new `latest` image

Add container image building to this repo
